config/routes.rb
ProjectSetup::Application.routes.draw do
  
  resources :medhistories

  resources :users
  
  resources :sessions, :only => [:new, :create,:destroy]
  
  resources :MedicalHistory, :only => [:create, :destroy]

  root :to => "pages#signin"
  get "pages/signup"

  get "pages/images"

  get "pages/doctors"

  get "pages/record"

  get "pages/about"

  get "pages/home"

  get "pages/contact"
  
  match '/pages/home', :to => "pages#home"
  
  match '/home', :to => "pages#home"
  
  match '/record', :to => "pages#record"
   
  match '/images', :to => "pages#images"
    
  match '/doctors', :to => "pages#doctors"
     
  match '/login', :to => "pages#login"
  
  match '/signup', :to => "users#new"
  
  match '/signin', :to => "sessions#new"
  
  match '/users/22/doctors', :to => "users#doctors"
  
  match '/signout', :to => "sessions#new"

end

app/models/medhistory.rb
class Medhistory < ActiveRecord::Base
end

app/controllers/medhistories_controller.rb
class MedhistoriesController < ApplicationController
  # GET /medhistories
  # GET /medhistories.json
  def index
    @medhistories = Medhistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @medhistories }
    end
  end

  # GET /medhistories/1
  # GET /medhistories/1.json
  def show
    @medhistory = Medhistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @medhistory }
    end
  end

  # GET /medhistories/new
  # GET /medhistories/new.json
  def new
    @medhistory = Medhistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @medhistory }
    end
  end

  # GET /medhistories/1/edit
  def edit
    @medhistory = Medhistory.find(params[:id])
  end

  # POST /medhistories
  # POST /medhistories.json
  def create
    @medhistory = Medhistory.new(params[:medhistory])

    respond_to do |format|
      if @medhistory.save
        format.html { redirect_to @medhistory, :notice => 'Medhistory was successfully created.' }
        format.json { render :json => @medhistory, :status => :created, :location => @medhistory }
      else
        format.html { render :action => "new" }
        format.json { render :json => @medhistory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /medhistories/1
  # PUT /medhistories/1.json
  def update
    @medhistory = Medhistory.find(params[:id])

    respond_to do |format|
      if @medhistory.update_attributes(params[:medhistory])
        format.html { redirect_to @medhistory, :notice => 'Medhistory was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @medhistory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /medhistories/1
  # DELETE /medhistories/1.json
  def destroy
    @medhistory = Medhistory.find(params[:id])
    @medhistory.destroy

    respond_to do |format|
      format.html { redirect_to medhistories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/medhistories_helper.rb
module MedhistoriesHelper
end

app/views/medhistories/_form.html.erb
<%= form_for(@medhistory) do |f| %>
  <% if @medhistory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medhistory.errors.count, "error") %> prohibited this medhistory from being saved:</h2>

      <ul>
      <% @medhistory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :history %><br />
    <%= f.text_field :history %>
  </div>
  <div class="field">
    <%= f.label :allergies %><br />
    <%= f.text_field :allergies %>
  </div>
  <div class="field">
    <%= f.label :familyhistory %><br />
    <%= f.text_field :familyhistory %>
  </div>
  <div class="field">
    <%= f.label :images %><br />
    <%= f.text_field :images %>
  </div>
  <div class="field">
    <%= f.label :appointments %><br />
    <%= f.text_field :appointments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medhistories/edit.html.erb
<h1>Editing medhistory</h1>

<%= render 'form' %>

<%= link_to 'Show', @medhistory %> |
<%= link_to 'Back', medhistories_path %>

app/views/medhistories/index.html.erb
<h1>Listing medhistories</h1>

<table>
  <tr>
    <th>History</th>
    <th>Allergies</th>
    <th>Familyhistory</th>
    <th>Images</th>
    <th>Appointments</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medhistories.each do |medhistory| %>
  <tr>
    <td><%= medhistory.history %></td>
    <td><%= medhistory.allergies %></td>
    <td><%= medhistory.familyhistory %></td>
    <td><%= medhistory.images %></td>
    <td><%= medhistory.appointments %></td>
    <td><%= link_to 'Show', medhistory %></td>
    <td><%= link_to 'Edit', edit_medhistory_path(medhistory) %></td>
    <td><%= link_to 'Destroy', medhistory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medhistory', new_medhistory_path %>

app/views/medhistories/new.html.erb
<h1>New medhistory</h1>

<%= render 'form' %>

<%= link_to 'Back', medhistories_path %>

app/views/medhistories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>History:</b>
  <%= @medhistory.history %>
</p>

<p>
  <b>Allergies:</b>
  <%= @medhistory.allergies %>
</p>

<p>
  <b>Familyhistory:</b>
  <%= @medhistory.familyhistory %>
</p>

<p>
  <b>Images:</b>
  <%= @medhistory.images %>
</p>

<p>
  <b>Appointments:</b>
  <%= @medhistory.appointments %>
</p>


<%= link_to 'Edit', edit_medhistory_path(@medhistory) %> |
<%= link_to 'Back', medhistories_path %>