config/routes.rb
ProjectSetup::Application.routes.draw do
  
  resources :medhistories

  resources :users
  
  resources :sessions, :only => [:new, :create,:destroy]
  
  resources :MedicalHistory, :only => [:create, :destroy]

  root :to => "pages#signin"
  get "pages/signup"

  get "pages/images"

  get "pages/doctors"

  get "pages/record"

  get "pages/about"

  get "pages/home"

  get "pages/contact"
  
  match '/pages/home', :to => "pages#home"
  
  match '/home', :to => "pages#home"
  
  match '/record', :to => "pages#record"
   
  match '/images', :to => "pages#images"
    
  match '/doctors', :to => "pages#doctors"
     
  match '/login', :to => "pages#login"
  
  match '/signup', :to => "users#new"
  
  match '/signin', :to => "sessions#new"
  
  match '/users/22/doctors', :to => "users#doctors"
  
  match '/signout', :to => "sessions#new"

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
 
  has_many :MedicalHistory, :dependent => :destroy
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => {:maximum => 50}
                   
  validates :email, :presence => true,
                    :format => {:with => email_regex},
                    :uniqueness => { :case_sensitive => false}
                    
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40}
                       
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  class << self
    def authenticate(email, submitted_password)
      user = find_by_email(email)
      (user && user.has_password?(submitted_password)) ? user : nil
    end
    
    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  
  private
     def encrypt_password
       self.salt = make_salt if new_record?
       self.encrypted_password = encrypt(password)
     end
     
     def encrypt(string)
        secure_hash("#{salt}--#{string}")
     end
     
     def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
     end
     
     def secure_hash(string)
       Digest::SHA2.hexdigest(string)       
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @title = @user.name
    @MedicalHistory = @user.MedicalHistory
    @MedicalHistory = MedicalHistory.new if signed_in?
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @title = "Sign up"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @title = "Edit User"   
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    #@user = User.new
    #if @user.save
    #  sign_in @user
    #  redirect_to @user, flash[:error] = "Welcome To your Personal Medical Record"
    #else
    #  @title = "Sign Up"
    #  render 'new'
    #end
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
  def doctors
    @user = User.find(params[:id])
    @title = @user.name

    respond_to do |format|
      format.html # doctors.html.erb
      format.json { render :json => @user }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options = { :size => 100})
    gravatar_image_tag(user.email.downcase, :alt => user.name, :class => 'gravatar', :gravatar => options)
  end
  
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages'%>
<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name%>
</div>
<div class="field">
	<%= f.label :email %>
	<%= f.text_field :email%>
</div>
<div class="field">
	<%= f.label :password %>
	<%= f.password_field :password%>
</div>
<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation%>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/doctors.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Website Name</title>

<%= stylesheet_link_tag 'home_style_sheet.css', :media => 'screen' %>

<style type="text/css">
.auto-style1 {
	text-align: right;
}
</style>
</head>

<body>
<div id="container">
	<div id="header">
		<h1>Personal Medical Record</h1>
	</div>
	<div id="navigation">
		<ul>
			
		</ul>
	</div>
	<div id="content-container">
		
		<div id="content">
			<h1>Editing user</h1>

			<%= form_for(@user) do |f| %>
				
				<%= render 'fields', :f => f %>
				
				<div class="actions">
					<%= f.submit "Update"%>
				</div>
			<% end %>
			
			<div class="action">
				<%= gravatar_for @user %>
				<a href="http://gravatar.com/emails" target=_blank>change</a>
			</div>

		</div>
		<div id="aside">
			<h3>
				Instructions
			</h3>
			<p>
				Edit the information for your account
			</p>
		</div>
		<div id="footer">
			Copyright © Site name, 2011
		</div>
	</div>
</div>
</body>

</html>

app/views/users/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Website Name</title>

<%= stylesheet_link_tag 'home_style_sheet.css', :media => 'screen' %>

<style type="text/css">
.auto-style1 {
	text-align: right;
}
</style>
</head>

<body>
<div id="container">
	<div id="header">
		<h1>Personal Medical Record</h1>
	</div>
	<div id="navigation">
		<ul>
			
		</ul>
	</div>
	<div id="content-container">
		
		<div id="content">
			<h1>Editing user</h1>

			<%= form_for(@user) do |f| %>
				
				<%= render 'fields', :f => f %>

				<div class="actions">
					<%= f.submit "Update"%>
				</div>
			<% end %>
			
			<div class="action">
				<%= gravatar_for @user %>
				<a href="http://gravatar.com/emails" target=_blank>change</a>
			</div>
			
			<div class="action">
				<%= link_to "Back", user_path(current_user)%>
			</div>
			

		</div>
		<div id="aside">
			<h3>
				Instructions
			</h3>
			<p>
				Edit the information for your account
			</p>
		</div>
		<div id="footer">
			Copyright © Site name, 2011
		</div>
	</div>
</div>
</body>

</html>	

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Website Name</title>

<%= stylesheet_link_tag 'home_style_sheet.css', :media => 'screen' %>

<style type="text/css">
.auto-style1 {
	text-align: right;
}
</style>
</head>

<body>
<div id="container">
	<div id="header">
		<h1>Personal Medical Record</h1>
	</div>
	<div id="navigation">
		<ul>
			
		</ul>
	</div>
	<div id="content-container">
		
		<div id="content">
			<h1>Sign up</h1>
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages'%>
				<div class="field">
					<%= f.label :name %>
					<%= f.text_field :name%>
				</div>
				<div class="field">
					<%= f.label :email %>
					<%= f.text_field :email%>
				</div>
				<div class="field">
					<%= f.label :password %>
					<%= f.password_field :password%>
				</div>
				<div class="field">
					<%= f.label :password_confirmation, "Confirmation" %>
					<%= f.password_field :password_confirmation%>
				</div>
				<div class="actions">
					<%= f.submit "Sign up"%>
				</div>
			<% end %>
		</div>
		<div id="aside">
			<h3>
				Instructions
			</h3>
			<p>
				Sign up to create your Personal Medical Record
			</p>
		</div>
		<div id="footer">
			Copyright © Site name, 2011
		</div>
	</div>
</div>
</body>

</html>

app/views/users/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<title>Website Name</title>

<%= stylesheet_link_tag 'home_style_sheet.css', :media => 'screen' %>

<style type="text/css">
.auto-style1 {
	text-align: right;
}
</style>
</head>

<body>
<div id="container">
	<div id="header">
		<h1>
			Personal Medical Record
		</h1>
	</div>
	<div id="navigation">
		<ul>
			<li><%= link_to "Home", user_path(current_user)%></li>	
			<li><%= link_to "Medical Record", record_path%></li>
			<li><%= link_to "Scans/Images", images_path %></li>
			<li><%= link_to "Doctors", doctors_path %></li>
			
			<% if signed_in? %>
				<li><%= link_to "Sign out", signout_path%></li>
				<% else %>
				<li><%= link_to "Sign in", signin_path%></li>
			<% end %>
		</ul>
	</div>
	<div id="content-container">
		
		<div id="content">
			<p id="notice"><%= notice %></p>
			<table class="profile" summary="Profile Information">
				<tr>
					<td class="main">
						<h1>
							<%= @user.name %><br/><br/>
			  				<%= image_tag "blank_profile.jpg", :alt => 'Pic' %>
			  			</h1>
						<h3>
							<br/>
							<strong>Name</strong> <%= @user.name %><br /">
							<strong>Email</strong> <%= @user.email %><br /">
				  			<strong>URL</strong> <%= link_to user_path(@user), @user %><br/>
							<%= link_to "update profile", edit_user_path(@user)%><br /"><br/>
							
							<% if @user.MedicalHistory.any? %>
								<table class="MedicalHistory" summary="Medical History">
									<%= render @MedicalHistory %> 
								</table>
							<% end %>
							
					
							
						</h3>
			  		</td>
			  			
			  		
				</tr>
			</table>

			<!--<%= link_to 'Edit', edit_user_path(@user) %> |
			<%= link_to 'Back', users_path %><br />
			-->
			<br/>
			<p style="height: 18px" class="auto-style1">
				&nbsp;</p>
			
		</div>
		<div id="aside">
			<h3>
				Instructions
			</h3>
			<p>
				Once you have created an account, log in. 
			</p>
		</div>
		<div id="footer">
			Copyright © Site name, 2011
		</div>
	</div>
</div>
</body>

</html>